// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjbkrxxjwgnlvurfbcsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqYmtyeHhqd2dubHZ1cmZiY3NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Njk4NzUsImV4cCI6MjA2MjI0NTg3NX0.FG4NpdlI6yZLpNE5j1G3ZOrpWVnhQi9sn98j13MmP5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);